version: 1
formatters:
  logFormatter:
    format: "%(asctime)s [%(levelname)s] (%(name)s) %(funcName)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: logFormatter
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: logFormatter
    filename: ./logs/like_synchronizer.log
    maxBytes: 10_485_760
    backupCount: 3
loggers:
  # Library loggers
  googleapiclient:
    level: ERROR
  google_auth_httplib2:
    level: ERROR
  google_auth_oauthlib:
    level: ERROR
  spotipy:
    level: ERROR
  urllib3:
    level: ERROR
  requests_oauthlib:
    level: ERROR
  # Own loggers
  like_synchronizer.youtube:
    level: INFO
  like_synchronizer.spotify:
    level: INFO
  like_synchronizer:
    level: DEBUG
root:
  level: DEBUG
  handlers:
    - console
    - file
disable_existing_loggers: false
